### ISSUE TITLE
Create a `latest` tag for actions.

### ISSUE THREAD

**Issue by jmacelroy** [okteto/actions#30]
Currently we only have versioned tags, i.e `v4.3` for our actions that are then released to the github marketplace. Our documentation uses the form of `<action>@master` everywhere meaning that users will always use the last commit. 

I believe we should introduce a new tag that is `latest` This tag would then be the documented default in our readme, website and anywhere we've described actions. We can then have latest point to the tip if we want but will be able to easily rollback or pin the action to introduce stability while we work on master.

**Comment by pchico83** [comment]
I think it is a great idea!
+1

**Comment by pchico83** [comment]
@jLopezbarb we can do it as part of the automation for each Okteto CLI release

**Comment by jLopezbarb** [comment]
Yes we can do it, but when we click on the release page it will not be at the top of the page.

**Comment by rberrelleza** [comment]
instead of `latest`, I think we should follow the common practice and use  `v1` (that's what most actions I saw seem to do, couldn't find any example that does `latest`).

**Comment by jmacelroy** [comment]
This is done.
