### ISSUE TITLE
How to use with Okteto Self Hosted?

### ISSUE THREAD

**Issue by bangbaew** [okteto/actions#32]
I've seen only the documentation for Okteto Cloud, is it possible for self hosted?
My Okteto self hosted is linked with my GitHub application.

**Comment by rberrelleza** [comment]
Yes, all our actions work with Okteto Self-Hosted. https://www.okteto.com/docs/cloud/preview-environments/preview-environments-github/#step-1-create-the-github-workflow includes a sample of how to use it.
