### ISSUE TITLE
Allow build action to use build-args

### ISSUE THREAD

**Issue by tullo** [okteto/actions#9]
I am looking into updating the build action to accept build-args as they now are supported by the latest release of okteto binary.

The **current version** of the action is using the okteto binary from the **docker image**.

But that binary is no longer part of the latest image as it seems

```console
docker container run --name okto --rm -it okteto/bin:1.1.5 ls /usr/local/bin/
remote      start.sh    supervisor  syncthing
```
Should I `curl` the latest binary into the image instead?

**Comment by rberrelleza** [comment]
closed by #10
